version: "3.9"

services:
  app:
    container_name: app
    image: app
    build:
      context: .
      dockerfile: nginx/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./browser:/public
    